name = "blog"
compatibility_date = "2025-04-19"
main = "workers-site/index.js"
account_id = "4aba88032362cabbf59b788550001d47"

[build]
command = "npm install && chmod +x build.sh && ./build.sh"

[vars]
  NEXT_PUBLIC_SANITY_PROJECT_ID = "6y69uwke"
  NEXT_PUBLIC_SANITY_DATASET = "production"
  NEXT_PUBLIC_SANITY_API_VERSION = "2024-10-28"
