[build]
command = "npm install && npm run build"
output_directory = "nextjs-app/.next"
base_directory = "."

[build.environment]
NODE_VERSION = "22"
NPM_VERSION = "10"
NEXT_PUBLIC_SANITY_PROJECT_ID = "6y69uwke"
NEXT_PUBLIC_SANITY_DATASET = "production"
NEXT_PUBLIC_SANITY_API_VERSION = "2024-10-28"
SANITY_API_READ_TOKEN = "skAVYRZmzigqDoeaqjvuY9R7NNBdfROI59gxjQUHW6HsUriJvik8VW0kliSvczWQyS7f59zHvtGPaOPqxm2ThhYmhZ6B4aqirGTYjLkM8fukXmlPjAfphItKUeHwrdOTvlka57M7sYsDnJHtCrIT8PM3xpN6KDziLZm6DoWhksIkwclmKyXd"

[site]
functions = "nextjs-app/.next/server/pages"

[routes]
  # Serve all static files from the static directory
  "/_next/static/*" = { type = "static", path = "nextjs-app/.next/static/*" }

  # Handle Next.js API routes
  "/api/*" = { type = "function", pattern = "/api/*" }

  # Handle all other routes with the default function
  "/*" = { type = "function", pattern = "/*" }
